lexik_jwt_authentication:
    secret_key: '%kernel.project_dir%/config/private.pem'  # Ruta a tu clave privada
    public_key: '%kernel.project_dir%/config/public.pem'   # Ruta a tu clave pública
    token_ttl: 3600                                            # Tiempo de vida del token en segundos

    ########################################################################################
  #                                                                                          #
 #                                                                                             #
#    ░█▀▀█ ▒█▀▀█ ▒█░▒█ ░█▀▀█ ▒█▄░▒█ ▀▀█▀▀ ▒█▀▀▀ 　 ▒█▀▀▀ ▒█░░░ 　 ▒█▀▀▀ ░█▀▀█ ▒█▀▀▀█ ▒█▀▀▀█     #
#    ▒█▄▄█ ▒█░▄▄ ▒█░▒█ ▒█▄▄█ ▒█▒█▒█ ░▒█░░ ▒█▀▀▀ 　 ▒█▀▀▀ ▒█░░░ 　 ▒█▀▀▀ ▒█▄▄█ ░▀▀▀▄▄ ▒█░░▒█     #
#    ▒█░▒█ ▒█▄▄█ ░▀▄▄▀ ▒█░▒█ ▒█░░▀█ ░▒█░░ ▒█▄▄▄ 　 ▒█▄▄▄ ▒█▄▄█ 　 ▒█░░░ ▒█░▒█ ▒█▄▄▄█ ▒█▄▄▄█     #
 #                                                                                             #

    ########################################################################################